apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: not-important-StatefulSet
annotations:
  configmanagement.gke.io/cluster-selector: anthos-on-gcp
fieldSpecs:
- kind: StatefulSet
  path: metadata/annotations
  create: true