resources:
- ../../base

namespace: boa

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: frontend
  path: ./kustomizeconfig/frontend-patch.yaml

- target:
    group: apps
    version: v1
    kind: Deployment
    name: balancereader
  path: ./kustomizeconfig/balancereader-patch.yaml

- target:
    group: apps
    version: v1
    kind: Deployment
    name: contacts
  path: ./kustomizeconfig/contacts-patch.yaml 
  
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ledgerwriter
  path: ./kustomizeconfig/ledgerwriter-patch.yaml
  
- target:
    group: apps
    version: v1
    kind: Deployment
    name: transactionhistory
  path: ./kustomizeconfig/transactionhistory-patch.yaml
  
- target:
    group: apps
    version: v1
    kind: Deployment
    name: userservice
  path: ./kustomizeconfig/userservice-patch.yaml
  
transformers:
- ./kustomizeconfig/suffix.yaml
- ./kustomizeconfig/deployment_annotation.yaml