- op: replace
  path: /spec/template/spec/containers/0/image
  value: gcr.io/bank-of-anthos-ci/loadgenerator:v0.5.6

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: FRONTEND_ADDR
      value: "frontend:80"
    - name: USERS
      value: "5"
    - name: LOG_LEVEL
      value: "error"