apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/general-objects

commonLabels:
  app: balancereader

replicas:
- name: __appname__
  count: 5

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: __appname__
  path: patches/deployment.yaml

patches:
- target:
    kind: Deployment|Service
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: balancereader
# - target:
#     kind: Deployment
#     name: .*
#   patch: |-
#     - op: add
#       path: /metadata/annotation
#       value:
#         haha: hihi

# transformers:
# - ./transformers/transform_annotation.yaml

components:
- ../../../components/cluster-patches/DC
- ../../../components/cluster-patches/DR
- ../../../components/common-env-patches/dev