- op: replace
  path: /spec/template/spec/containers/0/image
  value: gcr.io/bank-of-anthos-ci/balancereader:v0.5.6

- op: add
  path: /spec/template/spec/volumes
  value:
    - name: publickey
      secret:
        secretName: jwt-key
        items:
          - key: jwtRS256.key.pub
            path: publickey
    - emptyDir: {}
      name: tmp

- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: publickey
      mountPath: "/tmp/.ssh"
      readOnly: true
    - mountPath: /tmp
      name: tmp

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: VERSION
      value: "v0.5.6"
    - name: PORT
      value: "8080"
    # toggle Cloud Trace export
    - name: ENABLE_TRACING
      value: "true"
    - name: ENABLE_METRICS
      value: "true"
    - name: POLL_MS
      value: "100"
    - name: CACHE_SIZE
      value: "1000000"
    # tell Java to obey container memory limits
    - name: JVM_OPTS
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m"
    # Valid levels are debug, info, warn, error, fatal.
    # If no valid level is set, will default to info.
    - name: LOG_LEVEL
      value: "info"
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: LOCAL_ROUTING_NUM
      value: "883745000"
    - name: PUB_KEY_PATH
      value: "/tmp/.ssh/publickey"