apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: dev

patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /spec/template/spec/nodeSelector
      value:
        env: dev