- op: replace
  path: /spec/template/spec/containers/0/image
  value: gcr.io/bank-of-anthos-ci/ledgerwriter:v0.5.6

- op: add
  path: /spec/template/spec/volumes
  value:
    - name: publickey
      secret:
        secretName: jwt-key
        items:
          - key: jwtRS256.key.pub
            path: publickey
    - emptyDir: {}
      name: tmp

- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: publickey
      mountPath: "/tmp/.ssh"
      readOnly: true
    - mountPath: /tmp
      name: tmp

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: VERSION
      value: "v0.5.6"
    - name: PORT
      value: "8080"
    - name: ENABLE_TRACING
      value: "true"
    - name: ENABLE_METRICS
      value: "true"
     # tell Java to obey container memory limits
    - name: JVM_OPTS
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m"
    # service level override of log level
    - name: LOG_LEVEL
      value: "info"
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POSTGRES_DB
      value: postgresdb
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_PASSWORD
      value: password
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://ledger-db:5432/postgresdb
    - name: SPRING_DATASOURCE_USERNAME
      value: admin # should match POSTGRES_USER
    - name: SPRING_DATASOURCE_PASSWORD
      value: password # should match POSTGRES_PASSWORD
    - name: LOCAL_ROUTING_NUM
      value: "883745000"
    - name: PUB_KEY_PATH
      value: "/tmp/.ssh/publickey"
    - name: TRANSACTIONS_API_ADDR
      value: "ledgerwriter:8080"
    - name: BALANCES_API_ADDR
      value: "balancereader:8080"
    - name: HISTORY_API_ADDR
      value: "transactionhistory:8080"
    - name: CONTACTS_API_ADDR
      value: "contacts:8080"
    - name: USERSERVICE_API_ADDR
      value: "userservice:8080"