apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/shared-objects

secretGenerator:
- name: jwt-key
  files:
    - files/jwtRS256.key.pub
    - files/jwtRS256.key

generatorOptions:
  disableNameSuffixHash: true